FROM		alpine:latest

RUN 		apk add --no-cache libc6-compat

COPY		srcs ./root

WORKDIR		/root/

RUN			wget https://dl.grafana.com/oss/release/grafana-7.4.0.linux-amd64.tar.gz; \
			tar -zxvf grafana-7.4.0.linux-amd64.tar.gz; \
			rm grafana-7.4.0.linux-amd64.tar.gz; \
			mv grafana-7.4.0 grafana

EXPOSE		3000

ENTRYPOINT	["sh", "setup_container.sh"]