FROM		alpine:latest

RUN			apk update && apk add	nginx \
									wget \
									php7-fpm \
									php7-mysqli \
									php7-json 
COPY		srcs ./root/

WORKDIR		/root/

EXPOSE		5050

ENTRYPOINT	["sh", "setup_container.sh"]