FROM		alpine:latest

RUN			apk update && apk add	nginx \
									wget \
									php7-fpm \
									php7-mysqli \
									php7-json \
									php7-cli \
									php7-cgi \
									php7-mbstring \
									php7-opcache \
									php7-gd \
									php7-session \
									php7-zlib

COPY		srcs ./root/

WORKDIR		/root/

EXPOSE		5050

ENTRYPOINT	["sh", "setup_container.sh"]